export const SWAP_IN_KEY = 'REF_FI_SWAP_IN';
export const SWAP_OUT_KEY = 'REF_FI_SWAP_OUT';
export const SWAP_IN_KEY_SYMBOL = 'REF_FI_SWAP_IN_SYMBOL';
export const SWAP_OUT_KEY_SYMBOL = 'REF_FI_SWAP_OUT_SYMBOL';

export const SWAP_SLIPPAGE_KEY_LIMIT = 'REF_FI_SLIPPAGE_VALUE_LIMIT';


export const SWAP_SLIPPAGE_KEY = 'REF_FI_SLIPPAGE_VALUE';
